### ISSUE TITLE
How can I help wallabag

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1254]
Hello,

We'll list here all actions you can do in "wallasphere" (wallabag and all its projects) to help this project. This list will be often updated, stay tuned.

If you need to propose your new development, your fix, etc. please read [CONTRIBUTING](https://github.com/wallabag/wallabag/blob/master/CONTRIBUTING.md) and [GUIDELINES](https://github.com/wallabag/wallabag/blob/master/GUIDELINES.md) recommendations. 

If you want to make one of this task, please [create a new issue](https://github.com/wallabag/wallabag/issues/new), we'll reference your issue next to the task below.

#### v2.0

wallabag is still in development and we need some help. You can find this version here: https://github.com/wallabag/wallabag/tree/v2

You can have an overview of what is done here #1049.

##### wallabag core

- [x] implement oAuth2 https://github.com/wallabag/wallabag/pull/1287
- [ ] implement Elasticsearch (started here: https://github.com/wallabag/wallabag/tree/v2-es)
- [x] implement graby (a mission for @j0k3r I think) https://github.com/j0k3r/graby
- [ ] API missing endpoints #1432
- [ ] automatically update wallabag installation. @FreshRSS does it here https://github.com/FreshRSS/update.freshrss.org
- [ ] For enterprises, offer wallabag accounts based on a LDAP directory. LDAP Symfony bundles exist. Discussion at #966.
- [ ] Fetch content from password protected websites #438. wallabag currently can't fetch content from websites that are requiring an authentication to display content. We have two leads on how to deal with that : 
  - save http sessions and cookies and wallabag sends them : tricky solution, since every website has it's own method
  - use browser extensions to fetch content with javascript and then send it to wallabag : better solution, should work anywhere
- [ ] [many many others ideas](https://github.com/wallabag/wallabag/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0)

##### Features from v1 that still need to be implemented
- [ ] downloading pictures
- [x] ebook creation
- [ ] random article
- [ ] basic search (if no Elasticsearch)
- [x] export/import
- [ ] front-end tricks (keyboard, sharing services, ...)

##### Deployment

- [x] create docker image for wallabag v2

##### UX

- [x] new default theme
- [x] adapt baggy to v2

##### Tests

- [x] try to install wallabag v2 and try the existing features (listed here #1049)

````
git clone https://github.com/wallabag/wallabag.git -b v2
cd wallabag
composer install
php app/console wallabag:install
php app/console server:run
```
#### v1.9.x

#### site config files

Websites parsing is based on specific configuration files. Sometimes, websites parsing failed and wallabag users contact us with the article URL. You can find a list of these websites here: https://github.com/wallabag/fix-articles We also have [many issues here](https://github.com/wallabag/wallabag/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22Site+Config%22+).

A howto for write specific configuration files is available here:http://help.fivefilters.org/customer/portal/articles/223153-site-patterns

### support website http://support.wallabag.org

- [ ] migrate to Discourse (I sent an email to Framasoft team)
- [ ] make some clean up into questions

### translations

- [x] find the great tool to make translations easier (Transifex?)

### smartphone applications

#### FirefoxOS

#### Android

#### Windows Phone

#### iOS

#### Cross platform application
- [ ] Currently relying on reading RSS feeds, the mobile applications are missing a lot of features (mark as read, tags, category, searching) that can now be provided by the API included with v2.0. The new apps should take advantage of [all the possibilities](http://v2.wallabag.org/api/doc/) offered by the API. The app should be build with a cross-plateform framework, such as AngularJS and Cordova, so that the work can be reused on different systems. Knowledge prerequisites: _minimal_  html5, js, git, iOS *or* Android *or* Windows 8 apps *or* Firefox OS *or* Ubuntu Touch. _preferred_ : AngularJS, Cordova

Already in progress by @frankoa https://github.com/obtao/ionic-sandbox/tree/wallabag

### browser addons

#### Firefox

- [ ] `Bag this page` in contextual menu (Social API share menu does the trick)
- [ ] add a confirmation step before saving page with SocialAPI

#### Chrome

- [x] ~~`Bag this page` in contextual menu~~ (updated since 9/08/15)

#### Opera

- [x] ~~Adapt Chrome extension to Opera: Opera now uses the Chromium extension model, it should be fairly easy to support Opera too.~~ Opera works with the Chrome Extension.
- [ ] Publish extension on the Opera Store.

#### Extend the features of the Browser extensions
- [ ] Currently the extensions only consist in sending the window link to wallabag, nothing more. With v2, they should be capable to : 
  - show if the webpage has already been saved
  - directly tag the page just saved
  - change it's properties (starred, archive, deleted, etc)

### documentation website

- [ ] generate static documentation files for each release (to embed the latest documentation in the release). Need https://github.com/CouscousPHP/Couscous/issues/117 by @CouscousPHP 

### wallabag.org website

- [x] new design
- [x] integrate the nice presentation https://framabag.org/cquoi
- [x] add screenshots
- [ ] make a video to explain what wallabag / framabag is

### framabag.org

- [ ] today, some framabag users have empty articles or articles with "[unable to retrieve full-text content]" instead of content: I started a tool (written in PHP, with Symfony components) https://github.com/wallabag/framabag-reimport-entries. This tool will be launched by a cron to reimport these articles.
- [ ] The framabag.org website is ugly. It's written in old PHP. I started a Symfony application https://github.com/wallabag/framabag-sf, which is not ended. With this new website, each Framabag users will be able to disable its account.
- [ ] write a cron to contact inactive accounts
- [ ] maintenance mode when we upgrade Framabag
- [ ] add a donation part on framabag.org
- [ ] add a link to support website

### Misc

- [ ] automate release process
- [ ] automate production process
- [ ] migrate our projects to Gitlab (gitlab.com, git.framasoft.org) and synchronize projects with github.com
- [ ] community manager: write blog posts, communicate on social networks (Diaspora, twitter, Facebook, Google+), look for websites who talking about wallabag / framabag
- [ ] connect wallabag to IFTTT: Write IFTTT recipes to connect wallabag on determined actions. Ask IFTTT for a [partnership](https://docs.google.com/forms/d/1dlH6aA2nXQ4EWfQbxHKueHvfyulFPmInkjk7PabUxF8/viewform) for them to add a wallabag Channel (there are already Pocket, Instapaper and Readability channels).
- [ ] make linux install packages #1014: There have been attempts to create debian packages for wallabag, but they didn't succeed. We should have deb and rpm packages. wallabag is already in the [AUR](https://aur.archlinux.org/packages/wallabag) for archlinux.

**Comment by j0k3r** [comment]
The easiest way is to pick some issues from [Easy bug](https://github.com/wallabag/wallabag/labels/Easy%20bug) label.
