### ISSUE TITLE
Change database structure

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#620]
Before changing the structure, we have to list all the new fields we need. 

@tcitworld @mariroz please help me to fill this issue :-) 

**Entries**: 
* [x] date when entry was added
* [x] date of last edition
* [x] user comments (#1038)
* [x]  ~~author comments (#1033 or directly into main content)~~ it's content for me (nicosomb).  
* [x] mime_type
* [ ] if content contains multimedia ? #880
* [x] langugage of entry ?
* [x] preview picture (#972 - #840) ?
* [x] high-lighted text (#994)
* [x] reading_time (for #393) ?
* [x] *is_public* or *shared_with_group* (if you want to restrict the group, for instance to your coworkers, maybe better than completely public) #805
* [x] domain_name (is it really necessary ? Can't sorting by domain name be done only with selecting the beginning of each URL ?)
* [ ] suggested tags #719 ?
* [ ] author #629 

**Tags**:

**Users**:
* [ ] A LOT of options currently into config.inc.php (sharing buttons, display options...) #686
* [x] email (necessary in the new model)
* [x] is_admin
* [ ] LDAP (#966 and #967)

**Config**:

**Comment by nicosomb** [comment]
ping @tcitworld: 
Can you edit the first post with new structure if you think we have to add some fields, please?

**Comment by nicosomb** [comment]
For your information, I updated Entries structure (like the current 1st post): https://github.com/wallabag/wallabag/blob/34d15eb4d0544263d27650207b23bd046e509f74/src/Wallabag/CoreBundle/Entity/Entries.php

**Comment by tcitworld** [comment]
I had so much ideas... Let's hope I find them all again. :D

**Comment by nicosomb** [comment]
I close this issue: we have an issue for each missing field. To need to have this summary issue.
